# Deep Learning with PyTorch

### 1.5 Variables

**Objective**: Understand Variables and operations on them

In [14]:
import torch
from torch.autograd import Variable

Let's create a small computation graph

In [15]:
x = Variable(torch.FloatTensor([11.2]), requires_grad=True)
y = 2 * x

In [16]:
print(x)
print(y)

tensor([11.2000], requires_grad=True)
tensor([22.4000], grad_fn=<MulBackward0>)


In [17]:
print(x.data)
print(y.data)

tensor([11.2000])
tensor([22.4000])


In [18]:
print(x.grad_fn)
print(y.grad_fn)

None


In [19]:
y.backward() # Calculates the gradients

In [20]:
print(x.grad)
print(y.grad)

tensor([2.])
None
