# Deep Learning with PyTorch

### 1.6 Working with PyTorch and NumPy

In [2]:
import torch
import numpy as np

Convert a NumPy array to Tensor

In [6]:
n = np.array([2, 3])
t = torch.IntTensor(n)
t = torch.from_numpy(n)
print(n)
print(t)

[2 3]
tensor([2, 3])


Change a Tensor value, and see the change in 
corresponding NumPy array

In [7]:
n[0] = 100
print(t)

tensor([100,   3])


Convert a Tensor to NumPy array

In [8]:
t = torch.FloatTensor([5, 6])
n = t.numpy()
print(t)
print(n)

tensor([5., 6.])
[ 5.  6.]


Change a Tensor value, and see the change in corresponding NumPy array

In [9]:
t[0] = 100
print(n)

[ 100.    6.]
